version: '3'
services:      
  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aqueductepass
      - POSTGRES_DB=geologia
    image: mdillon/postgis
    networks:
      - default
    ports:
      - "5435:5432"
    restart: always
    volumes:
    - "./db/postgis:/var/lib/postgresql/data"
  
  api:
    container_name: "aqueducte-geo-data-py"
    build: .
    depends_on:
      - db
    ports:
      - "3333:3333"
    volumes:
      - ./app:/usr/src/app/app
    restart: always
    links:
      - db
    depends_on:
      - db