version: '3'
services:
  web:
    build: .
    container_name: "aqueducte-geo-data-py"
    ports:
      - "3333:3333"
      
  postgis:
    container_name: postgis_aqueducte_geo_data
    image: mdillon/postgis
    hostname: postgis_aqueducte_geo_data
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=aqueductepass
    volumes:
    - "./db/postgis:/var/lib/postgresql/data"